"""Where FLINT reads the corpus from, and where it writes its own outputs.

The PROV corpus is generated by the companion **AgentDojo-PROV** project. FLINT reads
the corpus *files only* (``prov/<attack>/*.json`` + ``*.transcript.json``,
``manifest.json``, ``checksums.sha256``) from that project's directory — the single
source of truth — and writes its *own* derived artefacts (sweep / metrics / budget
parquets and per-model figures) under ``results/``. Keeping the two apart means
regenerating the corpus in AgentDojo-PROV never clobbers FLINT's outputs (and FLINT's
outputs never pollute the corpus directory).

Both roots are overridable by environment variable:
  * ``FLINT_CORPUS_ROOT``  — corpus source (default: the AgentDojo-PROV project).
  * ``FLINT_OUTPUT_ROOT``  — FLINT's parquet/figure outputs (default: ``results/corpus-prov``).
"""
from __future__ import annotations

import os
from pathlib import Path

# Corpus source — the AgentDojo-PROV project's generated corpus. Override with
# FLINT_CORPUS_ROOT to point at a Zenodo download (DOI 10.5281/zenodo.21052314) or a
# local AgentDojo-PROV checkout; these relative defaults assume a sibling checkout.
#
# The corpus lives in the *code* repo of the split pair, not the manuscript repo —
# mirroring FLINT / flint-framework. That repo clones as ``agentdojo-prov`` from
# GitHub but is checked out as ``AgentDojo-PROV-framework`` on the author's machines,
# so both are tried. Probing the full ``corpus/corpus-prov`` path (not just the repo
# dir) keeps this correct on case-insensitive filesystems, where ``agentdojo-prov``
# also matches the corpus-less manuscript checkout ``AgentDojo-PROV``.
_CORPUS_CANDIDATES = (
    "../agentdojo-prov/corpus/corpus-prov",
    "../AgentDojo-PROV-framework/corpus/corpus-prov",
)
DEFAULT_CORPUS_ROOT = _CORPUS_CANDIDATES[0]

# FLINT's own outputs (parquets, figures), keyed by model dir name — stays in FLINT.
DEFAULT_OUTPUT_ROOT = "results/corpus-prov"


def corpus_root() -> Path:
    """Root holding ``<model>/prov/...`` corpus files (read-only, from AgentDojo-PROV).

    ``FLINT_CORPUS_ROOT`` wins outright when set. Otherwise the sibling-checkout
    candidates are probed in order and the first that exists is used, falling back
    to the first candidate so the error message names a sensible path.
    """
    env = os.environ.get("FLINT_CORPUS_ROOT")
    if env:
        return Path(env).expanduser()
    for candidate in _CORPUS_CANDIDATES:
        path = Path(candidate).expanduser()
        if path.is_dir():
            return path
    return Path(DEFAULT_CORPUS_ROOT).expanduser()


def output_root() -> Path:
    """Root where FLINT writes ``<model>/{sweep,metrics,budget_sweep}.parquet`` + figures."""
    return Path(os.environ.get("FLINT_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT)).expanduser()


def corpus_dir(model: str) -> Path:
    """Corpus model dir (``prov/``, ``manifest.json``) from the AgentDojo-PROV source."""
    return corpus_root() / model


def output_dir(model: str) -> Path:
    """FLINT output dir for a model (parquets, figures); created on demand by callers."""
    return output_root() / model


def iter_files(directory: Path, pattern: str) -> list[Path]:
    """Glob ``pattern`` under ``directory``, skipping macOS AppleDouble sidecars.

    A corpus copied to a non-HFS filesystem carries a ``._<name>`` sidecar for
    every file. Those match ordinary globs but are binary resource forks, not
    JSON, so an unguarded reader either crashes on them or --- worse --- counts
    them as traces. Every corpus reader in FLINT goes through this helper.

    Results are sorted, so callers get a deterministic order for free.
    """
    return sorted(p for p in directory.glob(pattern) if not p.name.startswith("._"))


def prov_docs(prov_dir: Path) -> list[Path]:
    """PROV-JSON documents under an attack subdirectory (excludes transcripts)."""
    return [p for p in iter_files(prov_dir, "*.json")
            if not p.name.endswith(".transcript.json")]


def transcripts(corpus: Path) -> list[Path]:
    """``<corpus>/prov/<attack>/*.transcript.json``, AppleDouble-free."""
    return iter_files(corpus, "prov/*/*.transcript.json")
