"""f_emb detector — Layer 2.

WL 1-hop neighborhood-hash structural anomaly detector — a faithful structural
(Prov-HIDS-style) baseline.

Scope: ALL entity nodes are examined by structure alone; f_emb does NOT read
adprov:integrity.  This is what makes it the structural baseline:
  - structural mimicry (changing a node's neighborhood) evades it (P2 / H1);
  - a trust-attribution relabel ⊥→⊤ does NOT evade it — relabelling leaves the
    structure unchanged, so the hash still matches (the complement of f_flow,
    which IS defeated by relabelling — P3 / H5).

Why scoping to all entities adds no benign false positives: in FLINT's taint
model only sink-consumed entities acquire the canonical "generated-then-used"
shape, and those are precisely the untrusted injection-surface nodes.  Trusted
tool outputs have no `used` out-edge, so they never match the canonical set —
examining them is free (verified empirically: # trusted-canonical = 0 on benign
read-only and write-involving graphs).  Reading integrity for scope was the lone
reason a relabel evaded f_emb, and it is removed here.

Hash computation: uses ONLY structural features (node_type, relation labels on
incident edges) — NOT adprov:integrity — so an adversary can evade f_emb by
changing the structural neighborhood of an entity without altering any label
(P2 / H1).  f_flow, which explicitly checks integrity labels and reachability,
is immune to this structural change (P1 / H2).

Canonical injection patterns: entity nodes generated by one activity
(wasGeneratedBy in-edge) and consumed by k activities (k used out-edges), for
k = 1 .. MAX_CANONICAL_OUT.  The multi-sink patterns (k > 1) arise in traces
where several prior ⊥ entities are wired to multiple sink activities — common
in complex workspace tasks such as user_task_13.

Structural mimicry (adversary.py) must add enough decoy edges to push every
matching entity past MAX_CANONICAL_OUT used-out edges, ensuring no entity's hash
remains in CANONICAL_INJECTION_HASHES.  The coupling is intentional and explicit:
the constant MAX_CANONICAL_OUT is exported so adversary.py can query it.

Continuous score API
--------------------
f_emb_score(G)  — fraction of entity nodes whose hash is in CANONICAL_INJECTION_HASHES.
                   Ranges [0, 1]; enables ROC curves and evasion-budget plots.
build_benign_profile(graphs) — collect all node hashes from benign graphs; returns a
                   frozenset used by f_emb_novelty / f_emb_novelty_score.
f_emb_novelty(G, benign_profile) — anomaly detector: True if any entity hash is absent
                   from the benign profile (novel = suspicious).
f_emb_novelty_score(G, benign_profile) — continuous novelty: fraction of entity nodes
                   with hashes unseen in the benign profile.
"""
from __future__ import annotations

import hashlib
import json
from collections.abc import Iterable

import networkx as nx

# Maximum number of `used` out-edges covered by the canonical hash set.
MAX_CANONICAL_OUT: int = 3


def _structural_node_hash(G: nx.DiGraph, n: str) -> str:
    """WL 1-hop neighborhood hash — structural features only (no integrity/role)."""
    node_type = G.nodes[n].get("node_type", "?")
    in_sig = sorted(
        (G.nodes[nb].get("node_type", "?"), G.edges[nb, n].get("relation", "?"))
        for nb in G.predecessors(n)
    )
    out_sig = sorted(
        (G.nodes[nb].get("node_type", "?"), G.edges[n, nb].get("relation", "?"))
        for nb in G.successors(n)
    )
    s = json.dumps({"t": node_type, "i": in_sig, "o": out_sig}, separators=(",", ":"))
    return hashlib.sha256(s.encode()).hexdigest()[:16]


def _canonical_hash_for_k(k: int) -> str:
    """Hash for an entity with one wasGeneratedBy in-edge and k used out-edges."""
    in_sig = [["activity", "wasGeneratedBy"]]
    out_sig = [["activity", "used"]] * k
    s = json.dumps({"t": "entity", "i": in_sig, "o": out_sig}, separators=(",", ":"))
    return hashlib.sha256(s.encode()).hexdigest()[:16]


# Build the full canonical set once at module load.
CANONICAL_INJECTION_HASHES: frozenset[str] = frozenset(
    _canonical_hash_for_k(k) for k in range(1, MAX_CANONICAL_OUT + 1)
)

# Back-compat alias for the single-k=1 hash (used in tests that import it directly).
_INJECTION_HASH: str = _canonical_hash_for_k(1)


def _entity_nodes(G: nx.DiGraph) -> list[str]:
    """All entity nodes — f_emb is integrity-agnostic (structural baseline)."""
    return [n for n, d in G.nodes(data=True) if d.get("node_type") == "entity"]


# ---------------------------------------------------------------------------
# Binary detector
# ---------------------------------------------------------------------------

def f_emb(G: nx.DiGraph) -> bool:
    """Return True iff any entity node's 1-hop structural hash is canonical.

    Integrity-agnostic: examines every entity node by structure, so a
    trust-attribution relabel (⊥→⊤) does not evade it; structural mimicry does (P2).
    """
    return any(
        _structural_node_hash(G, n) in CANONICAL_INJECTION_HASHES
        for n in _entity_nodes(G)
    )


# ---------------------------------------------------------------------------
# Continuous score — canonical-hash fraction
# ---------------------------------------------------------------------------

def f_emb_score(G: nx.DiGraph) -> float:
    """Fraction of entity nodes whose 1-hop hash is in CANONICAL_INJECTION_HASHES.

    Returns a value in [0, 1].  Used for ROC curves and evasion-budget plots.
    0 = no entity matches (fully evaded, or no entities present);
    1 = every entity node matches the canonical injection signature set.
    """
    entities = _entity_nodes(G)
    if not entities:
        return 0.0
    matches = sum(
        1 for n in entities
        if _structural_node_hash(G, n) in CANONICAL_INJECTION_HASHES
    )
    return matches / len(entities)


# ---------------------------------------------------------------------------
# Novelty-based (benign-profile) detector
# ---------------------------------------------------------------------------

def build_benign_profile(graphs: Iterable[nx.DiGraph]) -> frozenset[str]:
    """Collect all 1-hop structural hashes observed in a set of benign graphs.

    The returned frozenset is the 'known-benign' neighbourhood vocabulary.
    Nodes whose hash is NOT in this set are structurally novel — a sign of
    anomaly under a benign-trained detector.
    """
    seen: set[str] = set()
    for G in graphs:
        for n in G.nodes():
            seen.add(_structural_node_hash(G, n))
    return frozenset(seen)


def f_emb_novelty(G: nx.DiGraph, benign_profile: frozenset[str]) -> bool:
    """Return True iff any entity node has a hash not seen in benign_profile."""
    return any(
        _structural_node_hash(G, n) not in benign_profile
        for n in _entity_nodes(G)
    )


def f_emb_novelty_score(G: nx.DiGraph, benign_profile: frozenset[str]) -> float:
    """Fraction of entity nodes with structurally novel (unseen-in-benign) hashes.

    Higher = more anomalous.  0 = all entity structures seen in benign training.
    """
    entities = _entity_nodes(G)
    if not entities:
        return 0.0
    novel = sum(
        1 for n in entities
        if _structural_node_hash(G, n) not in benign_profile
    )
    return novel / len(entities)
